name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Pull changes â¬‡ï¸
        uses: actions/checkout@v3

      - name: Install SSH key âš™ï¸
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Install dependencies â¬‡ï¸
        run: |
          apt-get update -qq -y
          apt-get install -qq -y ostree
          apt-get install -qq -y git pkg-config python3-pip
          pip install "ostree-push @ git+https://github.com/dbnicholson/ostree-push@v1.1.0"

      - name: Setup OSTree repository ğŸ“¦âš™ï¸
        run: |
          ostree --repo=repo init --mode=archive-z2
          ostree remote add --if-not-exists --no-gpg-verify --repo=repo meisenzahl-daily 'http://ostree.meisenzahl.me/repo/daily'

      - name: Pull last OSTree commit ğŸ“¦â¬‡ï¸
        run: |
          ostree pull --depth=1 --repo=repo meisenzahl-daily io.elementary.desktop/x86_64/7

      - name: Push OSTree commit ğŸ“¦â¬†ï¸
        run: |
          ostree-push --repo repo ostree@ostree.meisenzahl.me:/srv/ostree/repo/daily

      # - name: Build repository ğŸš§ğŸ”¨
      #   run: ./scripts/build-repository.sh

      # - name: Cleanup ğŸš§ğŸ§¹
      #   run: rm -rf artifacts/io.elementary.desktop

      # - name: Bundle artifacts ğŸ“¦ğŸ”¨
      #   run: tar -czvf artifacts.tar.gz artifacts

      # - name: Upload artifacts ğŸ“¦â¬†ï¸
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts
      #     path: artifacts.tar.gz
